#!/bin/bash
#PBS -N met_genome
#PBS -l nodes=1:ppn=4
#PBS -l walltime=100:00:00
#PBS -l pmem=8gb
#PBS -q compute
#PBS -m abe
#PBS -o met_genome.stdout
#PBS -e met_genome.stderr
#PBS -P RDS-FSC-VirusRates-RW


module load beast/1.8.2
# Print the default PBS server
echo PBS default server is $PBS_DEFAULT
# Print the job's working directory and enter it.
echo Working directory is $PBS_O_WORKDIR
cd $PBS_O_WORKDIR
 
# Print some other environment information
echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo This jobs runs on the following processors:
NODES=`cat $PBS_NODEFILE`
echo $NODES
# Compute the number of processorsNPROCS=`wc -l < $PBS_NODEFILE`
echo This job has allocated $NPROCS nodes

beast -overwrite -beagle_off concat_clock_genes.xml
